version: '3.8'
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    environment:
      JINA_AUTH_TOKEN: $JINA_AUTH_TOKEN
    depends_on:
      - redis-server
    ports:
      - "8501:8501"

  redis-server:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: